Document: vimgdb
Title: Debian vimgdb Manual
Author: <insert document author here>
Abstract: This manual describes what vimgdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vimgdb/vimgdb.sgml.gz

Format: postscript
Files: /usr/share/doc/vimgdb/vimgdb.ps.gz

Format: text
Files: /usr/share/doc/vimgdb/vimgdb.text.gz

Format: HTML
Index: /usr/share/doc/vimgdb/html/index.html
Files: /usr/share/doc/vimgdb/html/*.html
